# The port to listen on.
port = 14776

# Allow encrypted file transfers.
allow_encryption = true

# Require encryption for all files.
require_encryption = false

# Configure how long file information is stored before it is removed (in seconds).
# The longer this is, the more time the uploader has to reconnect, and downloaders
# to check for its availability and metadata. -1 means the file will never expire.
default_file_expiry_time = 86400

# Maximum file expiry time that an uploader can specify.
# -1 means the file will never expire.
max_file_expiry_time = 86400

# Configure UDP timeout duration in milliseconds.
udp_timeout_duration = 30000

# TODO: Add some file size, download count or bandwidth limit? Maybe
#       this could be negotiated by the client too as part of the spec.
# TODO: Add configuration for expiring file data earlier than file info.
