# The port to listen on.
port = 14776

[https]
# Whether or not to enable HTTPS.
enabled = false
# Path to HTTPS certificate.
cert = ""
# Path to HTTPS private key.
key = ""

# TODO: Add configuration for encryption (mandatory, optional, disabled)
# TODO: Add configuration for supporting proxied and direct connections.
# TODO: Add configuration for UDP timeouts.
# TODO: Split TCP and UDP port options.
